name: Deploy Website to Netlify

on:
  push:
    branches:
      - main  # يتم التشغيل عند أي تغيير في الفرع الرئيسي

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Netlify
      uses: netlify/actions/cli@master
      with:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}       
